"""Pydantic response schemas for the Commerce API.

These are the public API contracts — what external clients see.
Keep them stable; any change here is a breaking API change.

CatalogListItemSchema  — lean, for the paginated list (fast queries)
ProductDetailSchema    — full, for the single-product page (includes pricing snapshot)

QuoteStatus is defined in yasargold_domain.pricing.quotes (the domain owns it);
imported here and re-exported so API callers have one import path.
"""
from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field

from yasargold_domain.pricing.quotes import QuoteStatus

__all__ = [
    "QuoteStatus",
    "CategorySchema",
    "CatalogListItemSchema",
    "PricingSnapshotSchema",
    "ProductDetailSchema",
    "GoldRateSchema",
    "CatalogPageSchema",
]


class CategorySchema(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    karat: str | None = None


class CatalogListItemSchema(BaseModel):
    """Lean projection used by GET /catalog/products (list)."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    item_code: str
    slug: str = Field(description="URL-safe identifier; derived from item_code until a dedicated slug column is added to the ERP")
    name: str
    karat: str | None = None
    weight: float | None = None
    net_gold_weight: float | None = Field(
        None, description="weight minus stones_weight (grams of gold only)"
    )
    has_stones: bool = False
    stock: int = 0
    category: CategorySchema | None = None


class PricingSnapshotSchema(BaseModel):
    """Live pricing context embedded in the product detail page.

    quote_valid_until = rate_timestamp + FRESH_TTL (90 s). If that timestamp
    is in the past the frontend should show the price as indicative only.

    gold_price_id: FK to the GoldPrice row used to compute this snapshot.
    Present for Audit: "why was this order X SAR?" traces back to an exact
    row in the gold_price table.

    quote_id: opaque token generated by the Reservation Engine (Sprint 3).
    Null until then, but in the contract from day one:
        GET /products/{slug}  →  pricing_snapshot.quote_id
        POST /reservations    →  { quote_id: "..." }
    """
    gold_rate_per_gram_24k: Decimal
    karat_rate_per_gram: Decimal = Field(description="Rate for this item's karat, derived from 24k spot")
    issued_at: datetime = Field(description="When this Quote was generated")
    rate_timestamp: datetime = Field(description="When the gold rate was fetched from the source")
    quote_valid_until: datetime
    status: QuoteStatus
    gold_price_id: int = Field(description="PK of the GoldPrice row used; audit reference")
    quote_id: str | None = Field(
        None,
        description="Opaque reservation token — null until the Reservation Engine is live (Sprint 3)"
    )
    pricing_engine_version: str = Field(
        description="Version of yasargold_domain.pricing.engine; bump when formula or rounding rules change"
    )


class ProductDetailSchema(BaseModel):
    """Full projection used by GET /catalog/products/{slug} (detail page)."""
    model_config = ConfigDict(from_attributes=True)

    id: int
    item_code: str
    slug: str
    name: str
    barcode: str | None = None
    karat: str | None = None
    weight: float | None = None
    net_gold_weight: float | None = Field(
        None, description="weight minus stones_weight (grams of gold only)"
    )
    has_stones: bool = False
    stones_weight: float | None = None
    stones_value: float | None = None
    count: int | None = None
    wage: float | None = None
    description: str | None = None
    stock: int = 0
    category: CategorySchema | None = None
    pricing_snapshot: PricingSnapshotSchema | None = Field(
        None, description="Live gold rate context; None when status is HALTED"
    )


class GoldRateSchema(BaseModel):
    price_per_gram_24k: Decimal
    fetched_at: datetime
    status: str


class CatalogPageSchema(BaseModel):
    items: list[CatalogListItemSchema]
    total: int
    page: int
    page_size: int
    gold_rate: GoldRateSchema | None = None
