import 'package:flutter/material.dart';
import 'report_models.dart';

/// كتالوج التقارير الافتراضي للنظام
class ReportCatalog {
  static List<ReportCategory> buildDefaultCatalog() {
    return [
      ReportCategory(
        id: 'financial',
        icon: Icons.account_balance_wallet,
        accentColor: const Color(0xFF1565C0),
        nameAr: 'التقارير المالية',
        nameEn: 'Financial Reports',
        reports: const [
          ReportDescriptor(
            id: 'admin_dashboard',
            icon: Icons.dashboard,
            titleAr: 'لوحة تحكم المدير',
            titleEn: 'Admin Dashboard',
            descriptionAr:
                'مؤشرات سريعة، مخططات، وتنبيهات من واقع دفتر الخزينة وإغلاق الورديات.',
            descriptionEn:
                'Quick KPIs, charts, and alerts from the ledger and shift closings.',
            route: 'admin_dashboard',
            type: ReportType.financial,
            available: true,
            requiresFilters: false,
          ),
          ReportDescriptor(
            id: 'analytics_dashboard',
            icon: Icons.insights,
            titleAr: 'لوحة التحليل الوزني',
            titleEn: 'Weighted Analytics Dashboard',
            descriptionAr:
                'تحليل تفاعلي للوزن المكافئ (بالعيار الرئيسي) والتدفقات النقدية حسب الفروع أو نوع العملية أو الموظف.',
            descriptionEn:
                'Interactive analysis of main-karat equivalent weight and cash flows by office, transaction type, or employee.',
            route: 'analytics_dashboard',
            type: ReportType.financial,
            available: true,
            requiresFilters: true,
          ),
          ReportDescriptor(
            id: 'income_statement',
            icon: Icons.trending_up,
            titleAr: 'قائمة الدخل',
            titleEn: 'Income Statement',
            descriptionAr:
                'تحليل الإيرادات والمصروفات والربح الصافي حسب الفترة.',
            descriptionEn:
                'Analyze revenues, expenses, and net profit by period.',
            route: 'income_statement',
            type: ReportType.financial,
            available: true,
            requiresFilters: true,
          ),
          ReportDescriptor(
            id: 'balance_sheet',
            icon: Icons.account_balance,
            titleAr: 'الميزانية العمومية',
            titleEn: 'Balance Sheet',
            descriptionAr: 'عرض الأصول والخصوم وحقوق الملكية بنهاية الفترة.',
            descriptionEn:
                'Show assets, liabilities, and equity at period end.',
            route: 'balance_sheet',
            type: ReportType.financial,
            requiresFilters: false,
          ),
          ReportDescriptor(
            id: 'cash_flow',
            icon: Icons.swap_vert_circle,
            titleAr: 'التدفقات النقدية',
            titleEn: 'Cash Flow',
            descriptionAr:
                'متابعة التدفقات النقدية من التشغيل والاستثمار والتمويل.',
            descriptionEn:
                'Track cash flows from operations, investing, financing.',
            route: 'cash_flow',
            type: ReportType.financial,
          ),
          ReportDescriptor(
            id: 'trial_balance',
            icon: Icons.balance,
            titleAr: 'ميزان المراجعة',
            titleEn: 'Trial Balance',
            descriptionAr: 'مراجعة الأرصدة الإجمالية حسب الحساب والعيار.',
            descriptionEn: 'Review total balances by account and karat.',
            route: 'trial_balance',
            type: ReportType.accounting,
            available: true,
            requiresFilters: true,
          ),
          ReportDescriptor(
            id: 'customer_balances_aging',
            icon: Icons.schedule,
            titleAr: 'تقرير أعمار الذمم للعملاء',
            titleEn: 'Customer Balances Aging',
            descriptionAr:
                'توزيع أرصدة العملاء على فترات الاستحقاق مع أبرز المتأخرين.',
            descriptionEn:
                'Distribute customer balances across aging buckets and highlight top overdue accounts.',
            route: 'customer_balances_aging',
            type: ReportType.accounting,
            available: true,
            requiresFilters: true,
          ),
        ],
      ),
      ReportCategory(
        id: 'sales',
        icon: Icons.point_of_sale,
        accentColor: const Color(0xFF2E7D32),
        nameAr: 'تقارير المبيعات',
        nameEn: 'Sales Reports',
        reports: const [
          ReportDescriptor(
            id: 'sales_overview',
            icon: Icons.receipt_long,
            titleAr: 'ملخص المبيعات',
            titleEn: 'Sales Overview',
            descriptionAr: 'مبيعات يومية/شهرية مع مؤشرات الوزن والقيمة.',
            descriptionEn:
                'Daily/monthly sales with weight and value indicators.',
            route: 'sales_overview',
            type: ReportType.sales,
            available: true,
          ),
          ReportDescriptor(
            id: 'sales_by_customer',
            icon: Icons.group,
            titleAr: 'المبيعات حسب العميل',
            titleEn: 'Sales by Customer',
            descriptionAr: 'تحليل العملاء الأعلى شراءً والأرصدة المرتبطة.',
            descriptionEn: 'Analyze top customers and related balances.',
            route: 'sales_by_customer',
            type: ReportType.sales,
            available: true,
          ),
          ReportDescriptor(
            id: 'sales_by_item',
            icon: Icons.inventory_2,
            titleAr: 'المبيعات حسب الصنف',
            titleEn: 'Sales by Item',
            descriptionAr: 'أداء الأصناف حسب العيار والوزن والربحية.',
            descriptionEn: 'Item performance by karat, weight, profitability.',
            route: 'sales_by_item',
            type: ReportType.sales,
            available: true,
          ),
          ReportDescriptor(
            id: 'sales_vs_purchases_trend',
            icon: Icons.auto_graph,
            titleAr: 'اتجاه المبيعات مقابل المشتريات',
            titleEn: 'Sales vs Purchases Trend',
            descriptionAr:
                'مقارنة الاتجاهات الزمنية للقيمة والوزن بين المبيعات والمشتريات.',
            descriptionEn:
                'Compare value and weight trends for sales versus purchases.',
            route: 'sales_vs_purchases_trend',
            type: ReportType.sales,
            available: true,
            requiresFilters: true,
          ),
        ],
      ),
      ReportCategory(
        id: 'inventory',
        icon: Icons.warehouse,
        accentColor: const Color(0xFFFF8F00),
        nameAr: 'تقارير المخزون',
        nameEn: 'Inventory Reports',
        reports: const [
          ReportDescriptor(
            id: 'inventory_status',
            icon: Icons.inventory,
            titleAr: 'حالة المخزون',
            titleEn: 'Inventory Status',
            descriptionAr: 'أرصدة المخزون الحالية حسب الصنف والعيار.',
            descriptionEn: 'Current inventory balance by item and karat.',
            route: 'inventory_status',
            type: ReportType.inventory,
            available: true,
          ),
          ReportDescriptor(
            id: 'inventory_movement',
            icon: Icons.sync_alt,
            titleAr: 'حركة المخزون',
            titleEn: 'Inventory Movement',
            descriptionAr: 'تتبع الإدخالات والإخراجات بحسب الفترة.',
            descriptionEn: 'Track incoming/outgoing movement over time.',
            route: 'inventory_movement',
            type: ReportType.inventory,
            available: true,
          ),
          ReportDescriptor(
            id: 'low_stock',
            icon: Icons.warning_amber,
            titleAr: 'أصناف منخفضة المخزون',
            titleEn: 'Low Stock Items',
            descriptionAr: 'كشف بالأصناف التي تحتاج إعادة طلب سريع.',
            descriptionEn: 'List items that require replenishment soon.',
            route: 'low_stock',
            type: ReportType.inventory,
            available: true,
            requiresFilters: false,
          ),
        ],
      ),
      ReportCategory(
        id: 'gold',
        icon: Icons.currency_bitcoin,
        accentColor: const Color(0xFFFFD700),
        nameAr: 'تقارير الذهب',
        nameEn: 'Gold Reports',
        reports: const [
          ReportDescriptor(
            id: 'gold_price_history',
            icon: Icons.timeline,
            titleAr: 'تاريخ أسعار الذهب',
            titleEn: 'Gold Price History',
            descriptionAr: 'رسم بياني لأسعار الذهب اليومية مع المقارنات.',
            descriptionEn: 'Historical daily gold price with comparisons.',
            route: 'gold_price_history',
            type: ReportType.gold,
            available: true,
            requiresFilters: true,
          ),
          ReportDescriptor(
            id: 'gold_position',
            icon: Icons.scale,
            titleAr: 'مركز الذهب',
            titleEn: 'Gold Position',
            descriptionAr: 'تحليل صافي الذهب حسب العيار والمؤسسة.',
            descriptionEn: 'Net gold position by karat and branch.',
            route: 'gold_position',
            type: ReportType.gold,
            available: true,
            requiresFilters: true,
          ),
          ReportDescriptor(
            id: 'employee_scrap_ledger',
            icon: Icons.badge_outlined,
            titleAr: 'عهدة ذهب الكسر (الموظفين)',
            titleEn: 'Employee Scrap Ledger',
            descriptionAr:
                'ملخص ذهب الكسر المستلم حسب العهدة (الموظف) مع إجماليات سريعة.',
            descriptionEn:
                'Scrap gold received grouped by employee custody with quick totals.',
            route: 'employee_scrap_ledger',
            type: ReportType.gold,
            available: true,
            requiresFilters: true,
          ),
        ],
      ),
      ReportCategory(
        id: 'payroll',
        icon: Icons.people_alt,
        accentColor: const Color(0xFF512DA8),
        nameAr: 'تقارير الموارد البشرية',
        nameEn: 'HR Reports',
        reports: const [
          ReportDescriptor(
            id: 'payroll_monthly',
            icon: Icons.insert_chart,
            titleAr: 'التقرير الشهري للرواتب',
            titleEn: 'Monthly Payroll Report',
            descriptionAr: 'رواتب الموظفين مع الخصومات والإضافات لكل شهر.',
            descriptionEn: 'Employees payroll with deductions and additions.',
            route: 'payroll_report',
            type: ReportType.payroll,
            available: true,
          ),
          ReportDescriptor(
            id: 'attendance_summary',
            icon: Icons.access_time,
            titleAr: 'ملخص الحضور والانصراف',
            titleEn: 'Attendance Summary',
            descriptionAr: 'تحليل حضور الموظفين ومتوسط الساعات.',
            descriptionEn: 'Analyze employees attendance and average hours.',
            route: 'attendance_summary',
            type: ReportType.payroll,
          ),
        ],
      ),
      ReportCategory(
        id: 'accounting',
        icon: Icons.receipt_long,
        accentColor: const Color(0xFF00897B),
        nameAr: 'دفاتر المحاسبة',
        nameEn: 'Accounting Ledgers',
        reports: const [
          ReportDescriptor(
            id: 'general_ledger',
            icon: Icons.menu_book,
            titleAr: 'دفتر الأستاذ العام',
            titleEn: 'General Ledger',
            descriptionAr: 'كافة الحركات المحاسبية مع الرصيد التراكمي.',
            descriptionEn: 'All journal entries with running balances.',
            route: 'general_ledger',
            type: ReportType.accounting,
            available: true,
          ),
          ReportDescriptor(
            id: 'account_statement',
            icon: Icons.account_tree,
            titleAr: 'كشف حساب تفصيلي',
            titleEn: 'Detailed Account Statement',
            descriptionAr: 'عرض تدفقات الحساب المختار حسب العيار والنقد.',
            descriptionEn:
                'Display flows of selected account by karat and cash.',
            route: 'account_statement',
            type: ReportType.accounting,
            available: true,
          ),
          ReportDescriptor(
            id: 'customer_statement',
            icon: Icons.person_search,
            titleAr: 'كشف حساب العملاء',
            titleEn: 'Customer Statement',
            descriptionAr: 'متابعة أرصدة العملاء والقيود المرتبطة بهم.',
            descriptionEn: 'Track customer balances and related entries.',
            route: 'customer_statement',
            type: ReportType.accounting,
          ),
        ],
      ),
    ];
  }
}
