"""add address fields to customer and supplier

Revision ID: 484b3b17c9f5
Revises: 6b40b0537133
Create Date: 2025-10-05 15:13:07.485598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484b3b17c9f5'
down_revision: Union[str, Sequence[str], None] = '6b40b0537133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customer_account_id', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_supplier_account_id', 'account', ['account_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_constraint('fk_supplier_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_account_id', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
