"""Update customer model with detailed address fields

Revision ID: 629572566614
Revises: 484b3b17c9f5
Create Date: 2025-10-05 21:14:09.050702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '629572566614'
down_revision: Union[str, Sequence[str], None] = '484b3b17c9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_line_1', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.drop_column('district')
        batch_op.drop_column('postal')
        batch_op.drop_column('street')
        batch_op.drop_column('building')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('postal', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('district', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('postal_code')
        batch_op.drop_column('state')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')

    # ### end Alembic commands ###
