"""remove_debit_credit_accounts_add_voucher_account_line

Revision ID: 7ff60cdf8f40
Revises: 94240dd7cb28
Create Date: 2025-10-11 01:50:50.142508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff60cdf8f40'
down_revision: Union[str, Sequence[str], None] = '94240dd7cb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # إنشاء جدول voucher_account_line الجديد
    op.create_table(
        'voucher_account_line',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('voucher_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('line_type', sa.String(length=10), nullable=False),
        sa.Column('amount_type', sa.String(length=10), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('karat', sa.Float(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='fk_voucher_account_line_account'),
        sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], name='fk_voucher_account_line_voucher', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # إنشاء الفهارس
    with op.batch_alter_table('voucher_account_line', schema=None) as batch_op:
        batch_op.create_index('ix_voucher_account_line_voucher_id', ['voucher_id'], unique=False)
    
    # إزالة الحقول القديمة من voucher
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_constraint('fk_voucher_debit_account', type_='foreignkey')
        batch_op.drop_constraint('fk_voucher_credit_account', type_='foreignkey')
        batch_op.drop_column('debit_account_id')
        batch_op.drop_column('credit_account_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # استعادة الحقول القديمة في voucher
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_account_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('debit_account_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_voucher_credit_account', 'account', ['credit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_voucher_debit_account', 'account', ['debit_account_id'], ['id'])
    
    # حذف جدول voucher_account_line
    with op.batch_alter_table('voucher_account_line', schema=None) as batch_op:
        batch_op.drop_index('ix_voucher_account_line_voucher_id')
    
    op.drop_table('voucher_account_line')

    # ### end Alembic commands ###
