"""Add approval workflow to Voucher

Revision ID: 8951696d497e
Revises: 5b0c9a4a9812
Create Date: 2025-10-28 20:39:50.039694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8951696d497e'
down_revision: Union[str, Sequence[str], None] = '5b0c9a4a9812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold_subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wage_subtotal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gold_tax_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wage_tax_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('apply_gold_tax', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_invoice_payment_method_id', 'payment_method', ['payment_method_id'], ['id'])

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('manufacturing_wage_per_gram',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_index('idx_item_code')
        batch_op.create_index(batch_op.f('ix_item_item_code'), ['item_code'], unique=True)

    op.execute("UPDATE journal_entry SET entry_number = 'JE-UNKNOWN-00000' WHERE entry_number IS NULL")
    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.alter_column('entry_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint('uq_journal_entry_entry_number', ['entry_number'])

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.alter_column('applicable_invoice_types',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.alter_column('applicable_invoice_types',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('journal_entry', schema=None) as batch_op:
        batch_op.drop_constraint('uq_journal_entry_entry_number', type_='unique')
        batch_op.alter_column('entry_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_item_code'))
        batch_op.create_index('idx_item_code', ['item_code'], unique=1)
        batch_op.alter_column('manufacturing_wage_per_gram',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('item_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_payment_method_id', type_='foreignkey')
        batch_op.drop_column('apply_gold_tax')
        batch_op.drop_column('wage_tax_total')
        batch_op.drop_column('gold_tax_total')
        batch_op.drop_column('wage_subtotal')
        batch_op.drop_column('gold_subtotal')

    # ### end Alembic commands ###
