"""add_debit_credit_accounts_to_voucher

Revision ID: 94240dd7cb28
Revises: 304c83940d8d
Create Date: 2025-10-11 01:07:32.222009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94240dd7cb28'
down_revision: Union[str, Sequence[str], None] = '304c83940d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit_account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credit_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_voucher_debit_account', 'account', ['debit_account_id'], ['id'])
        batch_op.create_foreign_key('fk_voucher_credit_account', 'account', ['credit_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voucher', schema=None) as batch_op:
        batch_op.drop_constraint('fk_voucher_credit_account', type_='foreignkey')
        batch_op.drop_constraint('fk_voucher_debit_account', type_='foreignkey')
        batch_op.drop_column('credit_account_id')
        batch_op.drop_column('debit_account_id')

    # ### end Alembic commands ###
