"""add_invoice_return_and_gold_type_fields

Revision ID: 9c5481740401
Revises: 2396868be166
Create Date: 2025-10-10 14:43:25.516362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5481740401'
down_revision: Union[str, Sequence[str], None] = '2396868be166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_invoice_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gold_type', sa.String(length=20), server_default='new', nullable=True))
        batch_op.create_foreign_key('fk_invoice_original_invoice', 'invoice', ['original_invoice_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoice_original_invoice', type_='foreignkey')
        batch_op.drop_column('gold_type')
        batch_op.drop_column('return_reason')
        batch_op.drop_column('original_invoice_id')

    # ### end Alembic commands ###
