"""Phase 2 Bonus: reversal columns on employee_bonus + bonus_clawback_candidate table

Revision ID: bonus_phase2_reversal_001
Revises: 20260519_goal_bonus_fields, inventory_count_blind_001, orders_001
Create Date: 2026-08-03

Impact:
  - ADD COLUMN employee_bonus.reversed_by  VARCHAR(100)  NULL
  - ADD COLUMN employee_bonus.reversed_at  DATETIME      NULL
  - ADD COLUMN employee_bonus.reversal_reason TEXT         NULL
  - ADD COLUMN employee_bonus.status update: 'reversed' becomes valid terminal from 'approved'
    (no DDL change needed — status is VARCHAR; state machine enforced in application layer)
  - CREATE TABLE bonus_clawback_candidate (informational only, no financial entries)

Destructive: NO — all new columns are nullable; new table; no data migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'bonus_phase2_reversal_001'
down_revision: Union[str, Sequence[str], None] = (
    '20260519_goal_bonus_fields',
    'inventory_count_blind_001',
    'orders_001',
)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── 1. Reversal columns on employee_bonus ────────────────────────────────
    op.add_column('employee_bonus',
        sa.Column('reversed_by', sa.String(100), nullable=True))
    op.add_column('employee_bonus',
        sa.Column('reversed_at', sa.DateTime, nullable=True))
    op.add_column('employee_bonus',
        sa.Column('reversal_reason', sa.Text, nullable=True))

    # ── 2. bonus_clawback_candidate ─────────────────────────────────────────
    # Informational record: "a return invoice was posted that may warrant
    # bonus reversal". No financial entries are created here; the accounting
    # decision is entirely manual via POST /bonuses/{id}/reverse.
    op.create_table(
        'bonus_clawback_candidate',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('bonus_id', sa.Integer,
                  sa.ForeignKey('employee_bonus.id', ondelete='CASCADE'),
                  nullable=False, index=True),
        sa.Column('return_invoice_id', sa.Integer,
                  sa.ForeignKey('invoice.id', ondelete='SET NULL'),
                  nullable=True, index=True),
        sa.Column('original_invoice_id', sa.Integer,
                  sa.ForeignKey('invoice.id', ondelete='SET NULL'),
                  nullable=True),
        # Human-readable note generated by the posting pipeline
        sa.Column('reason', sa.Text, nullable=True),
        sa.Column('status', sa.String(20), nullable=False,
                  server_default='open'),   # open | dismissed | actioned
        sa.Column('dismissed_by', sa.String(100), nullable=True),
        sa.Column('dismissed_at', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False,
                  server_default=sa.func.now()),
        # يمنع إنشاء مرشح مكرر لنفس (مكافأة × مرتجع) عند الإعادة أو التزامن
        sa.UniqueConstraint('bonus_id', 'return_invoice_id',
                            name='uq_clawback_bonus_return_invoice'),
    )


def downgrade() -> None:
    op.drop_table('bonus_clawback_candidate')
    op.drop_column('employee_bonus', 'reversal_reason')
    op.drop_column('employee_bonus', 'reversed_at')
    op.drop_column('employee_bonus', 'reversed_by')
