"""Domain identity types — typed wrappers that prevent ID confusion.

Using NewType means:
    reserve(item_id=123, reservation_id=456)  # wrong arg order
    reserve(item_id=ItemId(123), reservation_id=ReservationId(456))

The type checker (mypy / pyright) will catch the swap above at compile time.
At runtime these are plain int/str — zero overhead.

Convention:
    *Id: int  → FK to a database row (ERP tables)
    *Id: str  → opaque token generated by the domain (quote_id, reservation_id)
"""
from __future__ import annotations

from typing import NewType

# int-based — FK to rows in the ERP database
ItemId        = NewType("ItemId",        int)
GoldPriceId   = NewType("GoldPriceId",   int)
CustomerId    = NewType("CustomerId",    int)
BranchId      = NewType("BranchId",     int)

# str-based — opaque tokens generated by domain services
QuoteId          = NewType("QuoteId",          str)
ReservationId    = NewType("ReservationId",    str)
PaymentIntentId  = NewType("PaymentIntentId",  str)

# str-based — opaque labels from infrastructure (never branched on in domain)
PaymentProvider     = NewType("PaymentProvider",     str)
PaymentFailureReason = NewType("PaymentFailureReason", str)

# Orders
OrderId = NewType("OrderId", str)

# Shipping
ShipmentId = NewType("ShipmentId", str)
